### ISSUE TITLE
Nvidia/GPU Tweaks causes GPU driver errors results in black box type artifacts flickering on windows desktop..

### ISSUE THREAD

**Issue by RyzenAdvanced** [SanGraphic/QuickBoost#11]
Once applied the Nvidia/GPU Tweaks it causes GPU driver errors results in black box type artifacts flickering on windows desktop..

Windows 11 latest 22h2 update
RTX 3080 16GB 175W Laptop GPU
12700H CPU
64GB DDR5

Nvidia Driver latest:
527.37-notebook-win10-win11-64bit-international-dch-whql

The GPU/Nvidia tweaks once applied, in random programs, like Cinebench R23 could give blinking (coming and go away) artifacts in form of black small cubes. 

Once Nvidia driver was reinstalled to clean the tweaks - issue is gone.

The artifacts could come with and without GPU core OC and without VRAM OC.

Artifacts were something like those:
https://prnt.sc/qoObuyY1K3o7

**Comment by SanGraphic** [comment]
Fixed, thank you.
