### ISSUE TITLE
Windows Night night no longer working after use

### ISSUE THREAD

**Issue by HaydnG** [SanGraphic/QuickBoost#13]
I know this isn't exactly an issue with the application itself. But You may have some insight on what has caused this. I expect its one of the windows services that's been disabled. Any idea?

Windows nightLight is no longer taking effect after using quickboost.

**Comment by pklion** [comment]
It is because quickboost disables Connected Devices Platform Service.
https://github.com/SanGraphic/QuickBoost/blob/main/v2/DisableServices.bat#L32

**Comment by HaydnG** [comment]
Ah sweet, was looking for that :)

**Comment by HaydnG** [comment]
@pklion Do you have any idea which service is responsible for the Windows Snipping tool, cant for the life of me find it.

**Comment by pklion** [comment]
@HaydnG Sorry, but I'm not sure about it.

**Comment by HaydnG** [comment]
@SanGraphic  It might be worth having some separation for these 3 services, what do you think? I personally use Windows NightLight and the screenshot tool all the time.
