### ISSUE TITLE
[Improvement] Provide information about services and fix a TabletPC command

### ISSUE THREAD

**Issue by dennyamarojr** [SanGraphic/QuickBoost#17]
I discover this project today and I'm really the project. I find a few commands that needs an information so the user will know the problems that may have if disable the service list that is available in the project.

The first thing that I see is 4 services that needs an information, here's the services:

CaptureService, which is required by Snipping Tool, depending on windows version is Snip & Sketch
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\CaptureService" /v Start /t REG_DWORD /d "4" /f

PimIndexMaintenanceSvc which is Contact Data and is required by Microsoft Store. I discover this after disable a few services and restore a few services that I know that is required by MS Store and when the service was restored to the default state MS Store could download apps normally.
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PimIndexMaintenanceSvc" /v Start /t REG_DWORD /d "4" /f
DevicesFlowUserSvc is required by Bluetooth & Devices and also required to show the informations in Quick Settings in Windows 11, this needs to be checked in Windows 10.
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\DevicesFlowUserSvc" /v Start /t REG_DWORD /d "3" /f

Next is this command that needs to be fixed which is put the wrong location
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\TabletPC" /v "DoSvc" /t REG_DWORD /d 3 /f
The correct command is this one
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\DoSvc" /v "Start" /t REG_DWORD /d 3 /f

Data Sharing service is also been disabled which is required by Snipping tool. If disabled shows "Failed to open a file" error
Source: https://www.winhelponline.com/blog/snip-failed-to-open-the-file-error-in-snipping-tool-sketch-app/#:~:text=To%20fix%20the%20%E2%80%9CFailed%20to%20open%20the%20file%E2%80%9D,by%20clicking%20%E2%80%9CStart%E2%80%9D.%206%20Exit%20the%20Services%20console.
reg add "HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\DsSvc" /v "Start" /t REG_DWORD /d "4" /f

**Comment by JermaynCodes** [comment]
Hey, im using Windows 11 and for me Snipping Tool still dont work.

Can you help me with that?

**Comment by dennyamarojr** [comment]
Hi @JermaynCodes first of all what is the version of windows 11 and what error message are you getting?

**Comment by SanGraphic** [comment]
Added all the fixes, thank you!
