### ISSUE TITLE
Snipping Tool stopt working

### ISSUE THREAD

**Issue by Jermayn1** [SanGraphic/QuickBoost#18]
Hey, after I used QuickBoost.exe and applied all Tweaks Snipping Tool stopt working.

I still can open it but every time I try to create an ScreenShot via the Hotkey or directly in the program, nothing happens.

Can someone help me?

**Comment by dennyamarojr** [comment]
Hi @JermaynCodes As describe in my issue, here's the following cause of your issue
CaptureService, which is required by Snipping Tool, depending on windows version is Snip & Sketch
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\CaptureService" /v Start /t REG_DWORD /d "4" /f

Data Sharing service is also been disabled which is required by Snipping tool. If disabled shows "Failed to open a file" error
Source: https://www.winhelponline.com/blog/snip-failed-to-open-the-file-error-in-snipping-tool-sketch-app/#:~:text=To%20fix%20the%20%E2%80%9CFailed%20to%20open%20the%20file%E2%80%9D,by%20clicking%20%E2%80%9CStart%E2%80%9D.%206%20Exit%20the%20Services%20console.
reg add "HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\DsSvc" /v "Start" /t REG_DWORD /d "4" /f

**Comment by dennyamarojr** [comment]
To restore to default state of the services, run the following commands in CMD or powershell as admin
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\CaptureService" /v Start /t REG_DWORD /d "3" /f
reg add "HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\DsSvc" /v "Start" /t REG_DWORD /d "3" /f

**Comment by JermaynCodes** [comment]
Tysm, I will give it a try. 👍

**Comment by SanGraphic** [comment]
Issue resolved

**Comment by SanGraphic** [comment]
Issue resolved
