### ISSUE TITLE
Auto-Create System Restore Point

### ISSUE THREAD

**Issue by amakvana** [SanGraphic/QuickBoost#2]
`wmic /Namespace:\\root\default Path SystemRestore Call CreateRestorePoint "My Restore Point", 100, 12`

Replace "My Restore Point" with the name of the Restore Point you're creating. 

Batch file will need self-elevation in order for it to run successfully

**Comment by amakvana** [comment]
Any update on this?

**Comment by SanGraphic** [comment]
Will look into it right now :)

**Comment by SanGraphic** [comment]
Seems to be working now, Thanks!
