### ISSUE TITLE
cant open the file

### ISSUE THREAD

**Issue by specurial** [SanGraphic/QuickBoost#22]
hi 
its work on my windows 11
but i cant open it on fresh windows 10 (22H2 19045.3208) at all (no error btw) just nothing happen when i trying to open it
i have all NET Desktop Runtime 5.0.11 - 7.0.9 and all Microsoft Visual C x86-x64 installed

**Comment by specurial** [comment]
for who have same issue like me :
my problem solved by disable hyperthreading virtual machine hyper-v @ bios
<3 github

**Comment by SanGraphic** [comment]
Thanks!
