### ISSUE TITLE
error 0x800704b3 - Nas unreachable

### ISSUE THREAD

**Issue by simplemore** [SanGraphic/QuickBoost#27]
Hi there,
Just a little "bug". My NAS is not reachable anymore since the use of quickboost [Disable Unnecessary System Services] & [Disable Startup telemetry].

I guess it is just one or two services to re-engage to be able to reach my NAS. Do you have any suggestion? Am I the only one who experienced this thing.

I tried to run few services in relation with the netwrok. My driver is ok, internet is ok, but impossible to reach my NAS via name or Ip. (it works with another pc on my network)

Thank you.

**Comment by sumanblack666** [comment]
any solution for this ? i cant access my nas or map a netword drive as well
