### ISSUE TITLE
Little semantic things

### ISSUE THREAD

**Issue by amakvana** [SanGraphic/QuickBoost#3]
Not so much issues, but little semantic things looking through your code :)

For example, replacing the following:
```
C:\Users\%USERNAME%\AppData\Local\
C:\Users\%USERNAME%\AppData\Roaming\
C:\Users\%USERNAME%\
choice /C:123 /N /M "> Enter Your Choice on the Keyboard [1,2,3..] : "	
```

With:
```
%LOCALAPPDATA%\
%APPDATA%\
%USERPROFILE%\
choice /C:123 /M "> Enter Your Choice on the Keyboard: "	
```

The first 3 make the application more portable, to account for users who've decided to redirect their userprofile directories elsewhere except the C drive.

The `choice` command alteration allows displaying the _choiceKeys_ at the end of the prompt string dynamically, so if you have 4 choices, it will automatically show as [1,2,3,4], etc.

If I find anymore as I quickly scroll through, I'll update them inside here.

Hope that helps!

**Comment by SanGraphic** [comment]
sorry for the late reply, change added!
