### ISSUE TITLE
No Update ?

### ISSUE THREAD

**Issue by SarnaxLii** [SanGraphic/QuickBoost#6]
Add **functions** / **Reduce** unnecessary functions. I like your work files. it's really awesome

- Twaeks Support For Windows 11
- Added some NVIDIA functionality, I tested it and it didn't help.

**Comment by Overimagine1** [comment]
Windows 11 works just fine with QuickBoost, I tested it myself

**Comment by SanGraphic** [comment]
Complete Windows 11 redesign and overhaul is happening this week.
